@startuml
'https://plantuml.com/sequence-diagram

!include <logos/oauth>
!include <logos/dotnet>
!include <logos/firefox>

title "<$oauth>\nOAuth 2.1 Authorization Code Grant"

autonumber

actor "Resource Owner" as ro
participant "<$dotnet>\nClient" as client
participant "<$firefox>\nUser Agent" as ua
participant "Authorization Server" as authzserver

ro -> client: Access application
client -> ua: Authorization Request (with //client id// & //redirect uri// & //scopes//)
ua -> authzserver: Redirect to authorization endpoint
authzserver --> authzserver: Authorization Endpoint:\nValidate //client id// & //redirect uri//\n& evaluate scopes
ua <- authzserver: Render login form
ro --> ua: User provides credentials (i.e. username/password)
ua --> authzserver: Post user credentials
authzserver --> authzserver: Authorization Endpoint:\nAuthenticates user

ua <- authzserver: Redirect back to //redirect uri// with Authorization Code
client <- ua: Authorization Code

client -> authzserver: Request access token (with //authorization code// + //client id/client secret//)
authzserver --> authzserver: Token Endpoint:\nAuthenticates //client id/client secret//\n& validates //authorization code//\n& generates //access token// (+ //refresh token//)
client <-- authzserver: Access Token

@enduml