@startuml
'https://plantuml.com/sequence-diagram

!include <logos/oauth>
!include <logos/dotnet>

title "<$oauth>\nOAuth 2.0 Resource Owner Password Credentials Grant"

autonumber

actor "Resource Owner" as ro
participant "<$dotnet>\nClient" as client
participant "Authorization Server" as authzserver

ro -> client: username/password credentials
client -> authzserver: Request access token with username/password credentials\n(and //client_id// & //client_secret//)
authzserver -> authzserver: Token Endpoint:\nAuthenticates client with credentials\nand //client_id/client_secret//\n& issues //access token//)
client <-- authzserver: Access Token

@enduml