@startuml
'https://plantuml.com/sequence-diagram

!include <logos/oauth>
!include <logos/dotnet>
!include <logos/firefox>

title "<$oauth>\nOAuth 2.1 Client Credentials Grant"

autonumber

participant "<$dotnet>\nClient" as client
participant "Authorization Server" as authzserver

client -> authzserver: Client authentication (with //client_id// & //client_secret//)
authzserver --> authzserver: Token Endpoint:\nAuthenticates //client_id/client_secret//\n& generates //access token//)
client <-- authzserver: Access Token

@enduml