server:
  servlet:
    context-path: /client
  port: 9095
spring:
  security:
    oauth2:
      client:
        provider:
          auth0:
            issuer-uri: https://access-me.eu.auth0.com/
            user-name-attribute: name
          keycloak:
            issuer-uri: http://localhost:8080/realms/workshop
            user-name-attribute: name
          spring:
            issuer-uri: http://localhost:9000
            user-name-attribute: name
        registration:
          auth0:
            client-id: 'v13BSQLEZnw4N96V36dDdsGRd022isKe'
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
          keycloak:
            client-id: 'product-client'
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
          spring:
            client-id: 'demo-client-pkce'
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email

logging:
  level:
    org:
      springframework:
        security: debug

product:
  server:
    url: "http://localhost:9090/server"